import { owners, teams } from "./sweepstake-data";
import { calculateLeaderboard, getOwnerByTeam, getTeamFlag } from "./sweepstake";
import type { Match, MatchEvent, Standing } from "./providers/types";

const now = new Date("2026-06-14T18:00:00.000Z");

export const mockEvents: MatchEvent[] = [
  {
    id: "evt-spain-goal",
    fixtureId: "live-spain-cape-verde",
    type: "goal",
    team: "Spain",
    ownerId: "willie",
    minute: 62,
    player: "Pedri",
    message: "Spain goal, Willie celebration.",
    createdAt: new Date(now.getTime() - 4 * 60_000).toISOString(),
  },
  {
    id: "evt-brazil-goal",
    fixtureId: "live-brazil-germany",
    type: "goal",
    team: "Brazil",
    ownerId: "lucy",
    minute: 33,
    player: "Vinicius Jr.",
    message: "Brazil goal, Lucy celebration.",
    createdAt: new Date(now.getTime() - 9 * 60_000).toISOString(),
  },
  {
    id: "evt-england-eq",
    fixtureId: "live-england-usa",
    type: "goal",
    team: "England",
    ownerId: "patrick",
    minute: 74,
    player: "Bukayo Saka",
    message: "England equaliser, Patrick stress.",
    createdAt: new Date(now.getTime() - 13 * 60_000).toISOString(),
  },
  {
    id: "evt-france-win",
    fixtureId: "finished-france-panama",
    type: "full-time",
    team: "France",
    ownerId: "holly",
    minute: 90,
    message: "France win, Holly favourite energy.",
    createdAt: new Date(now.getTime() - 38 * 60_000).toISOString(),
  },
  {
    id: "evt-argentina-win",
    fixtureId: "finished-argentina-ghana",
    type: "qualification",
    team: "Argentina",
    ownerId: "luke-k",
    minute: 90,
    message: "Argentina win, Luke K insurance policy.",
    createdAt: new Date(now.getTime() - 72 * 60_000).toISOString(),
  },
];

export const mockLiveMatches: Match[] = [
  {
    id: "live-spain-cape-verde",
    utcDate: now.toISOString(),
    stage: "Group stage",
    group: "A",
    status: "live",
    minute: 62,
    homeTeam: "Spain",
    awayTeam: "Cape Verde",
    homeFlag: getTeamFlag("Spain"),
    awayFlag: getTeamFlag("Cape Verde"),
    homeOwnerId: "willie",
    awayOwnerId: "alice",
    homeScore: 2,
    awayScore: 1,
    venue: "Estadio Azteca",
    events: mockEvents.filter((event) => event.fixtureId === "live-spain-cape-verde"),
    ownerLine: "Willie is flying. Alice is sweating.",
  },
  {
    id: "live-brazil-germany",
    utcDate: now.toISOString(),
    stage: "Group stage",
    group: "B",
    status: "live",
    minute: 33,
    homeTeam: "Brazil",
    awayTeam: "Germany",
    homeFlag: getTeamFlag("Brazil"),
    awayFlag: getTeamFlag("Germany"),
    homeOwnerId: "lucy",
    awayOwnerId: "alice",
    homeScore: 1,
    awayScore: 0,
    venue: "MetLife Stadium",
    events: mockEvents.filter((event) => event.fixtureId === "live-brazil-germany"),
    ownerLine: "Lucy is making noise. Alice is in trouble.",
  },
  {
    id: "live-portugal-morocco",
    utcDate: now.toISOString(),
    stage: "Group stage",
    group: "C",
    status: "live",
    minute: 18,
    homeTeam: "Portugal",
    awayTeam: "Morocco",
    homeFlag: getTeamFlag("Portugal"),
    awayFlag: getTeamFlag("Morocco"),
    homeOwnerId: "luke-oc",
    awayOwnerId: "luke-oc",
    homeScore: 0,
    awayScore: 0,
    venue: "SoFi Stadium",
    events: [],
    ownerLine: "Luke O'C is conflicted but loving it.",
  },
  {
    id: "live-england-usa",
    utcDate: now.toISOString(),
    stage: "Group stage",
    group: "D",
    status: "live",
    minute: 74,
    homeTeam: "England",
    awayTeam: "United States",
    homeFlag: getTeamFlag("England"),
    awayFlag: getTeamFlag("United States"),
    homeOwnerId: "patrick",
    awayOwnerId: "holly",
    homeScore: 1,
    awayScore: 1,
    venue: "AT&T Stadium",
    events: mockEvents.filter((event) => event.fixtureId === "live-england-usa"),
    ownerLine: "Patrick and Holly are both pretending to be calm.",
  },
];

export const mockUpcomingFixtures: Match[] = [
  {
    id: "upcoming-france-japan",
    utcDate: "2026-06-15T19:00:00.000Z",
    stage: "Group stage",
    group: "E",
    status: "scheduled",
    homeTeam: "France",
    awayTeam: "Japan",
    homeFlag: getTeamFlag("France"),
    awayFlag: getTeamFlag("Japan"),
    homeOwnerId: "holly",
    awayOwnerId: "alice",
    venue: "BC Place",
  },
  {
    id: "upcoming-argentina-netherlands",
    utcDate: "2026-06-16T01:00:00.000Z",
    stage: "Group stage",
    group: "F",
    status: "scheduled",
    homeTeam: "Argentina",
    awayTeam: "Netherlands",
    homeFlag: getTeamFlag("Argentina"),
    awayFlag: getTeamFlag("Netherlands"),
    homeOwnerId: "luke-k",
    awayOwnerId: "tracey",
    venue: "Hard Rock Stadium",
  },
  {
    id: "upcoming-mexico-portugal",
    utcDate: "2026-06-16T22:00:00.000Z",
    stage: "Group stage",
    group: "G",
    status: "scheduled",
    homeTeam: "Mexico",
    awayTeam: "Portugal",
    homeFlag: getTeamFlag("Mexico"),
    awayFlag: getTeamFlag("Portugal"),
    homeOwnerId: "lucy",
    awayOwnerId: "luke-oc",
    venue: "Estadio Guadalajara",
  },
];

export const mockFixtures: Match[] = [
  ...mockLiveMatches,
  ...mockUpcomingFixtures,
  {
    id: "finished-france-panama",
    utcDate: "2026-06-14T15:00:00.000Z",
    stage: "Group stage",
    group: "E",
    status: "finished",
    homeTeam: "France",
    awayTeam: "Panama",
    homeFlag: getTeamFlag("France"),
    awayFlag: getTeamFlag("Panama"),
    homeOwnerId: "holly",
    awayOwnerId: "holly",
    homeScore: 3,
    awayScore: 0,
    events: mockEvents.filter((event) => event.fixtureId === "finished-france-panama"),
  },
  {
    id: "finished-argentina-ghana",
    utcDate: "2026-06-14T12:00:00.000Z",
    stage: "Group stage",
    group: "H",
    status: "finished",
    homeTeam: "Argentina",
    awayTeam: "Ghana",
    homeFlag: getTeamFlag("Argentina"),
    awayFlag: getTeamFlag("Ghana"),
    homeOwnerId: "luke-k",
    awayOwnerId: "luke-k",
    homeScore: 2,
    awayScore: 0,
    events: mockEvents.filter((event) => event.fixtureId === "finished-argentina-ghana"),
  },
];

export const mockStandings: Standing[] = teams.slice(0, 36).map((team, index) => ({
  group: team.group ?? "A",
  team: team.name,
  flag: team.flag,
  ownerId: team.ownerId,
  played: team.played,
  won: team.won,
  drawn: team.drawn,
  lost: team.lost,
  goalsFor: team.goalsFor,
  goalsAgainst: team.goalsAgainst,
  goalDifference: team.goalsFor - team.goalsAgainst,
  points: team.points,
  position: (index % 4) + 1,
  qualificationStatus: index % 4 < 2 ? "qualified" : index % 4 === 2 ? "possible" : "eliminated",
}));

export const mockLeaderboard = calculateLeaderboard(owners, teams, mockFixtures);

export const mockOwnerLines = Object.fromEntries(owners.map((owner) => [owner.id, `${owner.name}: ${owner.statusLine}`]));

export function attachOwnersToMatch(match: Match): Match {
  const homeOwner = getOwnerByTeam(match.homeTeam);
  const awayOwner = getOwnerByTeam(match.awayTeam);
  return {
    ...match,
    homeOwnerId: match.homeOwnerId ?? homeOwner?.id,
    awayOwnerId: match.awayOwnerId ?? awayOwner?.id,
    homeFlag: match.homeFlag || getTeamFlag(match.homeTeam),
    awayFlag: match.awayFlag || getTeamFlag(match.awayTeam),
  };
}
